// Generated by scripts/fetch-openmoji.mjs — do not edit by hand.
// OpenMoji 17.0.0, group "travel-places" (excluding time, sky-weather).
// Icons are CC BY-SA 4.0; see the Legal dialog for the attribution this ships with.

export interface OpenMojiIcon {
  /** Unicode codepoint(s), and the SVG's filename in src/assets/openmoji. */
  hexcode: string
  /** The character itself, handy for search and for a text fallback. */
  emoji: string
  /** Human-readable name, as OpenMoji annotates it. */
  name: string
  /** OpenMoji's own subgrouping — the natural way to section a picker. */
  subgroup: string
}

export const OPENMOJI_ICONS: OpenMojiIcon[] = [
  {
    "hexcode": "1F6CE",
    "emoji": "🛎️",
    "name": "bellhop bell",
    "subgroup": "hotel"
  },
  {
    "hexcode": "1F9F3",
    "emoji": "🧳",
    "name": "luggage",
    "subgroup": "hotel"
  },
  {
    "hexcode": "1F3E6",
    "emoji": "🏦",
    "name": "bank",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F9F1",
    "emoji": "🧱",
    "name": "brick",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3D7",
    "emoji": "🏗️",
    "name": "building construction",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3F0",
    "emoji": "🏰",
    "name": "castle",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3DB",
    "emoji": "🏛️",
    "name": "classical building",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3EA",
    "emoji": "🏪",
    "name": "convenience store",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3EC",
    "emoji": "🏬",
    "name": "department store",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3DA",
    "emoji": "🏚️",
    "name": "derelict house",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3ED",
    "emoji": "🏭️",
    "name": "factory",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E5",
    "emoji": "🏥",
    "name": "hospital",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E8",
    "emoji": "🏨",
    "name": "hotel",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E0",
    "emoji": "🏠️",
    "name": "house",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E1",
    "emoji": "🏡",
    "name": "house with garden",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3D8",
    "emoji": "🏘️",
    "name": "houses",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F6D6",
    "emoji": "🛖",
    "name": "hut",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3EF",
    "emoji": "🏯",
    "name": "Japanese castle",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E3",
    "emoji": "🏣",
    "name": "Japanese post office",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E9",
    "emoji": "🏩",
    "name": "love hotel",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E2",
    "emoji": "🏢",
    "name": "office building",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3E4",
    "emoji": "🏤",
    "name": "post office",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1FAA8",
    "emoji": "🪨",
    "name": "rock",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3EB",
    "emoji": "🏫",
    "name": "school",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3DF",
    "emoji": "🏟️",
    "name": "stadium",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F5FD",
    "emoji": "🗽",
    "name": "Statue of Liberty",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F5FC",
    "emoji": "🗼",
    "name": "Tokyo tower",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F492",
    "emoji": "💒",
    "name": "wedding",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1FAB5",
    "emoji": "🪵",
    "name": "wood",
    "subgroup": "place-building"
  },
  {
    "hexcode": "1F3D6",
    "emoji": "🏖️",
    "name": "beach with umbrella",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F3D5",
    "emoji": "🏕️",
    "name": "camping",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F3DC",
    "emoji": "🏜️",
    "name": "desert",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F3DD",
    "emoji": "🏝️",
    "name": "desert island",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F6D8",
    "emoji": "🛘",
    "name": "landslide",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F5FB",
    "emoji": "🗻",
    "name": "mount fuji",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "26F0",
    "emoji": "⛰️",
    "name": "mountain",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F3DE",
    "emoji": "🏞️",
    "name": "national park",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F3D4",
    "emoji": "🏔️",
    "name": "snow-capped mountain",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F30B",
    "emoji": "🌋",
    "name": "volcano",
    "subgroup": "place-geographic"
  },
  {
    "hexcode": "1F9ED",
    "emoji": "🧭",
    "name": "compass",
    "subgroup": "place-map"
  },
  {
    "hexcode": "1F30E",
    "emoji": "🌎️",
    "name": "globe showing Americas",
    "subgroup": "place-map"
  },
  {
    "hexcode": "1F30F",
    "emoji": "🌏️",
    "name": "globe showing Asia-Australia",
    "subgroup": "place-map"
  },
  {
    "hexcode": "1F30D",
    "emoji": "🌍️",
    "name": "globe showing Europe-Africa",
    "subgroup": "place-map"
  },
  {
    "hexcode": "1F310",
    "emoji": "🌐",
    "name": "globe with meridians",
    "subgroup": "place-map"
  },
  {
    "hexcode": "1F5FE",
    "emoji": "🗾",
    "name": "map of Japan",
    "subgroup": "place-map"
  },
  {
    "hexcode": "1F5FA",
    "emoji": "🗺️",
    "name": "world map",
    "subgroup": "place-map"
  },
  {
    "hexcode": "1F488",
    "emoji": "💈",
    "name": "barber pole",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F309",
    "emoji": "🌉",
    "name": "bridge at night",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F3A0",
    "emoji": "🎠",
    "name": "carousel horse",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F3AA",
    "emoji": "🎪",
    "name": "circus tent",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F3D9",
    "emoji": "🏙️",
    "name": "cityscape",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F306",
    "emoji": "🌆",
    "name": "cityscape at dusk",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F3A1",
    "emoji": "🎡",
    "name": "ferris wheel",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F301",
    "emoji": "🌁",
    "name": "foggy",
    "subgroup": "place-other"
  },
  {
    "hexcode": "26F2",
    "emoji": "⛲️",
    "name": "fountain",
    "subgroup": "place-other"
  },
  {
    "hexcode": "2668",
    "emoji": "♨️",
    "name": "hot springs",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F303",
    "emoji": "🌃",
    "name": "night with stars",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F6DD",
    "emoji": "🛝",
    "name": "playground slide",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F3A2",
    "emoji": "🎢",
    "name": "roller coaster",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F305",
    "emoji": "🌅",
    "name": "sunrise",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F304",
    "emoji": "🌄",
    "name": "sunrise over mountains",
    "subgroup": "place-other"
  },
  {
    "hexcode": "1F307",
    "emoji": "🌇",
    "name": "sunset",
    "subgroup": "place-other"
  },
  {
    "hexcode": "26FA",
    "emoji": "⛺️",
    "name": "tent",
    "subgroup": "place-other"
  },
  {
    "hexcode": "26EA",
    "emoji": "⛪️",
    "name": "church",
    "subgroup": "place-religious"
  },
  {
    "hexcode": "1F6D5",
    "emoji": "🛕",
    "name": "hindu temple",
    "subgroup": "place-religious"
  },
  {
    "hexcode": "1F54B",
    "emoji": "🕋",
    "name": "kaaba",
    "subgroup": "place-religious"
  },
  {
    "hexcode": "1F54C",
    "emoji": "🕌",
    "name": "mosque",
    "subgroup": "place-religious"
  },
  {
    "hexcode": "26E9",
    "emoji": "⛩️",
    "name": "shinto shrine",
    "subgroup": "place-religious"
  },
  {
    "hexcode": "1F54D",
    "emoji": "🕍",
    "name": "synagogue",
    "subgroup": "place-religious"
  },
  {
    "hexcode": "1F6A1",
    "emoji": "🚡",
    "name": "aerial tramway",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "2708",
    "emoji": "✈️",
    "name": "airplane",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F6EC",
    "emoji": "🛬",
    "name": "airplane arrival",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F6EB",
    "emoji": "🛫",
    "name": "airplane departure",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F6F8",
    "emoji": "🛸",
    "name": "flying saucer",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F681",
    "emoji": "🚁",
    "name": "helicopter",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F6A0",
    "emoji": "🚠",
    "name": "mountain cableway",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1FA82",
    "emoji": "🪂",
    "name": "parachute",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F680",
    "emoji": "🚀",
    "name": "rocket",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F6F0",
    "emoji": "🛰️",
    "name": "satellite",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F4BA",
    "emoji": "💺",
    "name": "seat",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F6E9",
    "emoji": "🛩️",
    "name": "small airplane",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F69F",
    "emoji": "🚟",
    "name": "suspension railway",
    "subgroup": "transport-air"
  },
  {
    "hexcode": "1F691",
    "emoji": "🚑️",
    "name": "ambulance",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F69B",
    "emoji": "🚛",
    "name": "articulated lorry",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6FA",
    "emoji": "🛺",
    "name": "auto rickshaw",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F697",
    "emoji": "🚗",
    "name": "automobile",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6B2",
    "emoji": "🚲️",
    "name": "bicycle",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F685",
    "emoji": "🚅",
    "name": "bullet train",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F68C",
    "emoji": "🚌",
    "name": "bus",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F68F",
    "emoji": "🚏",
    "name": "bus stop",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6A7",
    "emoji": "🚧",
    "name": "construction",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F69A",
    "emoji": "🚚",
    "name": "delivery truck",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F692",
    "emoji": "🚒",
    "name": "fire engine",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "26FD",
    "emoji": "⛽️",
    "name": "fuel pump",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F684",
    "emoji": "🚄",
    "name": "high-speed train",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6A5",
    "emoji": "🚥",
    "name": "horizontal traffic light",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6F4",
    "emoji": "🛴",
    "name": "kick scooter",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F688",
    "emoji": "🚈",
    "name": "light rail",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F682",
    "emoji": "🚂",
    "name": "locomotive",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F9BD",
    "emoji": "🦽",
    "name": "manual wheelchair",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F687",
    "emoji": "🚇️",
    "name": "metro",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F690",
    "emoji": "🚐",
    "name": "minibus",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F69D",
    "emoji": "🚝",
    "name": "monorail",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6F5",
    "emoji": "🛵",
    "name": "motor scooter",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F3CD",
    "emoji": "🏍️",
    "name": "motorcycle",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F9BC",
    "emoji": "🦼",
    "name": "motorized wheelchair",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6E3",
    "emoji": "🛣️",
    "name": "motorway",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F69E",
    "emoji": "🚞",
    "name": "mountain railway",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6E2",
    "emoji": "🛢️",
    "name": "oil drum",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F698",
    "emoji": "🚘️",
    "name": "oncoming automobile",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F68D",
    "emoji": "🚍️",
    "name": "oncoming bus",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F694",
    "emoji": "🚔️",
    "name": "oncoming police car",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F696",
    "emoji": "🚖",
    "name": "oncoming taxi",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6FB",
    "emoji": "🛻",
    "name": "pickup truck",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F693",
    "emoji": "🚓",
    "name": "police car",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6A8",
    "emoji": "🚨",
    "name": "police car light",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F3CE",
    "emoji": "🏎️",
    "name": "racing car",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F683",
    "emoji": "🚃",
    "name": "railway car",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6E4",
    "emoji": "🛤️",
    "name": "railway track",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6FC",
    "emoji": "🛼",
    "name": "roller skate",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6F9",
    "emoji": "🛹",
    "name": "skateboard",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F699",
    "emoji": "🚙",
    "name": "sport utility vehicle",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F689",
    "emoji": "🚉",
    "name": "station",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6D1",
    "emoji": "🛑",
    "name": "stop sign",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F695",
    "emoji": "🚕",
    "name": "taxi",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F69C",
    "emoji": "🚜",
    "name": "tractor",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F686",
    "emoji": "🚆",
    "name": "train",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F68A",
    "emoji": "🚊",
    "name": "tram",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F68B",
    "emoji": "🚋",
    "name": "tram car",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F68E",
    "emoji": "🚎",
    "name": "trolleybus",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6A6",
    "emoji": "🚦",
    "name": "vertical traffic light",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "1F6DE",
    "emoji": "🛞",
    "name": "wheel",
    "subgroup": "transport-ground"
  },
  {
    "hexcode": "2693",
    "emoji": "⚓️",
    "name": "anchor",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "1F6F6",
    "emoji": "🛶",
    "name": "canoe",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "26F4",
    "emoji": "⛴️",
    "name": "ferry",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "1F6E5",
    "emoji": "🛥️",
    "name": "motor boat",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "1F6F3",
    "emoji": "🛳️",
    "name": "passenger ship",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "1F6DF",
    "emoji": "🛟",
    "name": "ring buoy",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "26F5",
    "emoji": "⛵️",
    "name": "sailboat",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "1F6A2",
    "emoji": "🚢",
    "name": "ship",
    "subgroup": "transport-water"
  },
  {
    "hexcode": "1F6A4",
    "emoji": "🚤",
    "name": "speedboat",
    "subgroup": "transport-water"
  }
]
